
package com.mycompany.twit;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//import javax.swing.JOptionPane;


public class Iniciar_Sesion extends javax.swing.JFrame {


    public Iniciar_Sesion() {
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(Color.BLACK);

        //Logo
        ImageIcon iconLogo = new ImageIcon("Logo3.png");
        Image imgLogo = iconLogo.getImage();
        Image imgScaleLogo = imgLogo.getScaledInstance(LabelLogo.getWidth(), LabelLogo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIconLogo = new ImageIcon(imgScaleLogo);
        LabelLogo.setIcon(scaledIconLogo);

        //Continuar
        ImageIcon iconContinuar = new ImageIcon("Continuar.png");
        Image imgContinuar = iconContinuar.getImage();
        Image imgScaleContinuar = imgContinuar.getScaledInstance(btn_Continuar.getWidth(), btn_Continuar.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIconContinuar = new ImageIcon(imgScaleContinuar);
        btn_Continuar.setIcon(scaledIconContinuar);

        //Cancelar
        ImageIcon iconCancelar = new ImageIcon("Cancelar.png");
        Image imgCancelar = iconCancelar.getImage();
        Image imgScaleCancelar = imgCancelar.getScaledInstance(btn_Cancelar.getWidth(), btn_Cancelar.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIconCancelar = new ImageIcon(imgScaleCancelar);
        btn_Cancelar.setIcon(scaledIconCancelar);

        //Continuar
        ImageIcon iconRegistro = new ImageIcon("Registrate.png");
        Image imgRegistro = iconRegistro.getImage();
        Image imgScaleRegistro = imgRegistro.getScaledInstance(btn_Registro.getWidth(), btn_Registro.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIconRegistro = new ImageIcon(imgScaleRegistro);
        btn_Registro.setIcon(scaledIconRegistro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelLogo = new javax.swing.JLabel();
        btn_Cancelar = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelIngresar = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        btn_Continuar = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        btn_Registro = new javax.swing.JLabel();
        jLabelRegistrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelLogo.setText("Logo");
        LabelLogo.setBounds(new java.awt.Rectangle(70, 50, 50, 50));
        LabelLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelLogoMouseClicked(evt);
            }
        });

        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CancelarMouseClicked(evt);
            }
        });

        jLabelUsuario.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(204, 204, 204));
        jLabelUsuario.setText("Usuario");

        jLabelIngresar.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIngresar.setText("Ingresa tus datos");

        jLabelContraseña.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(204, 204, 204));
        jLabelContraseña.setText("Contraseña");

        btn_Continuar.setText("Continuar");
        btn_Continuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Continuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ContinuarMouseClicked(evt);
            }
        });

        jTextFieldUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUsuario.setToolTipText("");
        jTextFieldUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });

        jPasswordField.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        btn_Registro.setText("Registro");
        btn_Registro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_RegistroMouseClicked(evt);
            }
        });

        jLabelRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistrar.setText("¿No tienes una cuenta? Registrate Aquí");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                            .addComponent(jPasswordField))
                        .addGap(18, 18, 18)
                        .addComponent(btn_Continuar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelRegistrar)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(252, 252, 252))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(LabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabelIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Continuar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelLogoMouseClicked
        new Menu_Inicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelLogoMouseClicked

    private void btn_CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelarMouseClicked
        new Menu_Inicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_CancelarMouseClicked

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void btn_ContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ContinuarMouseClicked
        String usuari = jTextFieldUsuario.getText().trim();
        String contra = jPasswordField.getText().trim();
        boolean encontrado= false;
        for (int i = 0; i < UsuarioInfo.getContador(); i++) {
        UsuarioInfo cuenta = UsuarioInfo.getCuenta(i);
        if (cuenta.getusuario().equals(usuari) && cuenta.getcontraseña().equals(contra)) {
            encontrado = true;
            user_actual.setUsuarioActual(cuenta);
            break;
        }
    }

        if (encontrado) {
           JOptionPane.showMessageDialog(null, "Inicio de sesión exitoso\nBienvenido");
           Inicio menu = new Inicio();
           menu.setVisible(true);
           this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Usuario o Contraseña erronea o cuenta inexistente");
        }
        
    }//GEN-LAST:event_btn_ContinuarMouseClicked

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void btn_RegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RegistroMouseClicked
        new Registrar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_RegistroMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JLabel btn_Cancelar;
    private javax.swing.JLabel btn_Continuar;
    private javax.swing.JLabel btn_Registro;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelIngresar;
    private javax.swing.JLabel jLabelRegistrar;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
