
package com.mycompany.twit;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;


public class Inicio extends javax.swing.JFrame {


    public Inicio() {
        initComponents();
        new Menu_Inicio().setLocationRelativeTo(null);

        this.setSize(1000, 740);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(Color.BLACK);

        //Logo
        ImageIcon iconLogo = new ImageIcon("Logo3.png");
        Image imgLogo = iconLogo.getImage();
        Image imgScaleLogo = imgLogo.getScaledInstance(LabelLogo.getWidth(), LabelLogo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIconLogo = new ImageIcon(imgScaleLogo);
        LabelLogo.setIcon(scaledIconLogo);

        //Timeline
        ImageIcon iconTimeline = new ImageIcon("Timeline.png");
        Image imgTimeline = iconTimeline.getImage();
        Image imgScaleTimeline = imgTimeline.getScaledInstance(btn_Timeline.getWidth(), btn_Timeline.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIconTimeline = new ImageIcon(imgScaleTimeline);
        btn_Timeline.setIcon(scaledIconTimeline);

        //Mandar Tweet
        ImageIcon iconMandar_Tweet = new ImageIcon("Mandar_Tweet.png");
        Image imgMandar_Tweet = iconMandar_Tweet.getImage();
        Image imgScaleMandar_Tweet = imgMandar_Tweet.getScaledInstance(btn_Interacciones.getWidth(), btn_Interacciones.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIconMandar_Tweet = new ImageIcon(imgScaleMandar_Tweet);
        btn_MandarTweet.setIcon(scaledIconMandar_Tweet);

        //Interacciones
        ImageIcon iconInteracciones = new ImageIcon("Interacciones.png");
        Image imgInteracciones = iconInteracciones.getImage();
        Image imgScaleInteracciones = imgInteracciones.getScaledInstance(btn_Interacciones.getWidth(), btn_Interacciones.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIconInteracciones = new ImageIcon(imgScaleInteracciones);
        btn_Interacciones.setIcon(scaledIconInteracciones);

        //Editar Perfil
        ImageIcon iconEditar_Perfil = new ImageIcon("Editar_Perfil.png");
        Image imgEditar_Perfil = iconEditar_Perfil.getImage();
        Image imgScaleEditar_Perfil = imgEditar_Perfil.getScaledInstance(btn_EditarPerfil.getWidth(), btn_EditarPerfil.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIconEditar_Perfil = new ImageIcon(imgScaleEditar_Perfil);
        btn_EditarPerfil.setIcon(scaledIconEditar_Perfil);

        //Buscar Hashtag
        ImageIcon iconBuscar = new ImageIcon("Buscar_Hashtag.png");
        Image imgBuscar = iconBuscar.getImage();
        Image imgScaleBuscar = imgBuscar.getScaledInstance(btn_BuscarHashtag.getWidth(), btn_BuscarHashtag.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIconBuscar = new ImageIcon(imgScaleBuscar);
        btn_BuscarHashtag.setIcon(scaledIconBuscar);

        //Cerrar Sesión
        ImageIcon iconCerrar_Sesion = new ImageIcon("Cerrar_Sesion.png");
        Image imgCerrar_Sesion = iconCerrar_Sesion.getImage();
        Image imgScaleCerrar_Sesion = imgCerrar_Sesion.getScaledInstance(btn_CerrarSesion.getWidth(), btn_CerrarSesion.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIconCerrar_Sesion = new ImageIcon(imgScaleCerrar_Sesion);
        btn_CerrarSesion.setIcon(scaledIconCerrar_Sesion);

        jInternalFrame.setSize(740, 660);
        InternalTimeline interTimeline = new InternalTimeline();
        jInternalFrame.add(interTimeline);
        interTimeline.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        LabelLogo = new javax.swing.JLabel();
        jLabelTwit = new javax.swing.JLabel();
        btn_Timeline = new javax.swing.JLabel();
        btn_Interacciones = new javax.swing.JLabel();
        btn_EditarPerfil = new javax.swing.JLabel();
        btn_BuscarHashtag = new javax.swing.JLabel();
        btn_CerrarSesion = new javax.swing.JLabel();
        jInternalFrame = new javax.swing.JInternalFrame();
        btn_MandarTweet = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelLogo.setText("Logo");
        LabelLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelLogoMouseClicked(evt);
            }
        });
        getContentPane().add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 128, 110));

        jLabelTwit.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabelTwit.setForeground(new java.awt.Color(0, 255, 255));
        jLabelTwit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTwit.setText("Twit");
        jLabelTwit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabelTwit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 103, 33));

        btn_Timeline.setText("Timeline");
        btn_Timeline.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Timeline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TimelineMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Timeline, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 175, 50));

        btn_Interacciones.setText("Interacciones");
        btn_Interacciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Interacciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_InteraccionesMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Interacciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 175, 50));

        btn_EditarPerfil.setText("Editar Perfil");
        btn_EditarPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_EditarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EditarPerfilMouseClicked(evt);
            }
        });
        getContentPane().add(btn_EditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 175, 50));

        btn_BuscarHashtag.setText("Buscar Hashtag");
        btn_BuscarHashtag.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_BuscarHashtag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BuscarHashtagMouseClicked(evt);
            }
        });
        getContentPane().add(btn_BuscarHashtag, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 175, 50));

        btn_CerrarSesion.setText("Cerrar Sesión");
        btn_CerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CerrarSesionMouseClicked(evt);
            }
        });
        getContentPane().add(btn_CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 175, 50));

        jInternalFrame.setBackground(new java.awt.Color(0, 0, 0));
        jInternalFrame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jInternalFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jInternalFrame.setVisible(true);
        getContentPane().add(jInternalFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 740, 660));

        btn_MandarTweet.setText("Mandar Tweet");
        btn_MandarTweet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_MandarTweet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_MandarTweetMouseClicked(evt);
            }
        });
        getContentPane().add(btn_MandarTweet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 175, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelLogoMouseClicked
        InternalTimeline interTimeline = new InternalTimeline();
        jInternalFrame.getContentPane().removeAll();
        jInternalFrame.add(interTimeline);
        interTimeline.setVisible(true);
    }//GEN-LAST:event_LabelLogoMouseClicked

    private void btn_CerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CerrarSesionMouseClicked
        new Menu_Inicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_CerrarSesionMouseClicked

    private void btn_TimelineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TimelineMouseClicked
        InternalTimeline interTimeline = new InternalTimeline();
        jInternalFrame.getContentPane().removeAll();
        jInternalFrame.add(interTimeline);
        interTimeline.setVisible(true);
    }//GEN-LAST:event_btn_TimelineMouseClicked

    private void btn_InteraccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_InteraccionesMouseClicked
        InternalInteracciones interInteracciones = new InternalInteracciones();
        jInternalFrame.getContentPane().removeAll();
        jInternalFrame.add(interInteracciones);
        interInteracciones.setVisible(true);
    }//GEN-LAST:event_btn_InteraccionesMouseClicked

    private void btn_EditarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditarPerfilMouseClicked
        InternalEditarPerfil interEditarPerfil = new InternalEditarPerfil();
        jInternalFrame.getContentPane().removeAll();
        jInternalFrame.add(interEditarPerfil);
        interEditarPerfil.setVisible(true);
    }//GEN-LAST:event_btn_EditarPerfilMouseClicked

    private void btn_BuscarHashtagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BuscarHashtagMouseClicked
        InternalBuscarHashtag interBuscarHashtag = new InternalBuscarHashtag();
        jInternalFrame.getContentPane().removeAll();
        jInternalFrame.add(interBuscarHashtag);
        interBuscarHashtag.setVisible(true);
    }//GEN-LAST:event_btn_BuscarHashtagMouseClicked

    private void btn_MandarTweetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MandarTweetMouseClicked
        InternalMandarTweet interMandarTweet = new InternalMandarTweet();
        jInternalFrame.getContentPane().removeAll();
        jInternalFrame.add(interMandarTweet);
        interMandarTweet.setVisible(true);
    }//GEN-LAST:event_btn_MandarTweetMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JLabel btn_BuscarHashtag;
    private javax.swing.JLabel btn_CerrarSesion;
    private javax.swing.JLabel btn_EditarPerfil;
    private javax.swing.JLabel btn_Interacciones;
    private javax.swing.JLabel btn_MandarTweet;
    private javax.swing.JLabel btn_Timeline;
    private javax.swing.JInternalFrame jInternalFrame;
    private javax.swing.JLabel jLabelTwit;
    private javax.swing.JMenu jMenu1;
    // End of variables declaration//GEN-END:variables
}
