package com.mycompany.twit;

public class InternalTimeline extends javax.swing.JInternalFrame {

    private UsuarioInfo verTwits;

    public InternalTimeline() {
        initComponents();
        
        verTwits = new UsuarioInfo();
        
        String[] twits = verTwits.obtenerTwits(); 
        int contador = verTwits.obtenerContadorTwits(); 
        StringBuilder textosConcatenados = new StringBuilder();

        for (int i = 0; i < contador; i++) {
            textosConcatenados.append(twits[i]).append("\n");
        }
        
        jTextAreaTimeline.setText(textosConcatenados.toString());
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTimeline = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaTimeline = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTimeline.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        jLabelTimeline.setForeground(new java.awt.Color(0, 255, 255));
        jLabelTimeline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTimeline.setText("Timeline");
        getContentPane().add(jLabelTimeline, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 280, 70));

        jTextAreaTimeline.setEditable(false);
        jTextAreaTimeline.setBackground(new java.awt.Color(0, 0, 0));
        jTextAreaTimeline.setColumns(20);
        jTextAreaTimeline.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        jTextAreaTimeline.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaTimeline.setLineWrap(true);
        jTextAreaTimeline.setRows(5);
        jTextAreaTimeline.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jScrollPane1.setViewportView(jTextAreaTimeline);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 680, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTimeline;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaTimeline;
    // End of variables declaration//GEN-END:variables
}
