package com.mycompany.twit;

import javax.swing.DefaultListModel;
import javax.swing.JList;

public class InternalBuscarPersona extends javax.swing.JInternalFrame {

    DefaultListModel<String> listmodel = new DefaultListModel<>();

    public InternalBuscarPersona() {
        initComponents();
        jListResultadosPersonas.setModel(listmodel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldBuscarPersona = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListResultadosPersonas = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldBuscarPersona.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldBuscarPersona.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTextFieldBuscarPersona.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldBuscarPersona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        getContentPane().add(jTextFieldBuscarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 87, 353, 50));

        btnBuscar.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 86, 85, 50));

        jListResultadosPersonas.setBackground(new java.awt.Color(0, 0, 0));
        jListResultadosPersonas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jListResultadosPersonas.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jListResultadosPersonas.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jListResultadosPersonas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 155, 450, 250));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese el usuario que desea buscar:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 63, 232, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        String palabraUser = jTextFieldBuscarPersona.getText();
        listmodel.clear();  // Limpiar los resultados anteriores

        
        String[] resultados = UsuarioInfo.buscarUsuariosConSeguimiento(palabraUser, user_actual.getUsuarioActual());

        
        for (String resultado : resultados) {
            listmodel.addElement(resultado);
        }
        
    }//GEN-LAST:event_btnBuscarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListResultadosPersonas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldBuscarPersona;
    // End of variables declaration//GEN-END:variables
}
