
package com.mycompany.twit;

public class InternalEditarPerfil extends javax.swing.JInternalFrame {


    public InternalEditarPerfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabelEditarPerfil = new javax.swing.JLabel();
        btn_BuscarPersona = new javax.swing.JLabel();
        btn_DesActivarCuenta = new javax.swing.JLabel();
        InternalFrameEditar = new javax.swing.JInternalFrame();
        btn_EntrarPerfil = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEditarPerfil.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        jLabelEditarPerfil.setForeground(new java.awt.Color(0, 255, 255));
        jLabelEditarPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEditarPerfil.setText("Editar Perfil");
        getContentPane().add(jLabelEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 300, 70));

        btn_BuscarPersona.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_BuscarPersona.setForeground(new java.awt.Color(255, 255, 255));
        btn_BuscarPersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_BuscarPersona.setText("Buscar Persona");
        btn_BuscarPersona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        btn_BuscarPersona.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_BuscarPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BuscarPersonaMouseClicked(evt);
            }
        });
        getContentPane().add(btn_BuscarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 175, 50));

        btn_DesActivarCuenta.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_DesActivarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btn_DesActivarCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_DesActivarCuenta.setText("Desactivar Cuenta");
        btn_DesActivarCuenta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        btn_DesActivarCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_DesActivarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DesActivarCuentaMouseClicked(evt);
            }
        });
        getContentPane().add(btn_DesActivarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 175, 50));

        InternalFrameEditar.setBackground(new java.awt.Color(0, 0, 0));
        InternalFrameEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        InternalFrameEditar.setForeground(new java.awt.Color(255, 255, 255));
        InternalFrameEditar.setVisible(true);

        javax.swing.GroupLayout InternalFrameEditarLayout = new javax.swing.GroupLayout(InternalFrameEditar.getContentPane());
        InternalFrameEditar.getContentPane().setLayout(InternalFrameEditarLayout);
        InternalFrameEditarLayout.setHorizontalGroup(
            InternalFrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );
        InternalFrameEditarLayout.setVerticalGroup(
            InternalFrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(InternalFrameEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 660, 440));

        btn_EntrarPerfil.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_EntrarPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btn_EntrarPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_EntrarPerfil.setText("Entrar a un Perfil");
        btn_EntrarPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        btn_EntrarPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_EntrarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EntrarPerfilMouseClicked(evt);
            }
        });
        getContentPane().add(btn_EntrarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 175, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BuscarPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BuscarPersonaMouseClicked
        InternalFrameEditar.getContentPane().removeAll();
        InternalFrameEditar.setVisible(true);
        InternalBuscarPersona interBuscarPersona = new InternalBuscarPersona();
        InternalFrameEditar.add(interBuscarPersona);
        interBuscarPersona.setVisible(true);
    }//GEN-LAST:event_btn_BuscarPersonaMouseClicked

    private void btn_DesActivarCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DesActivarCuentaMouseClicked
        InternalFrameEditar.getContentPane().removeAll();
        InternalFrameEditar.setVisible(true);
        InternalDesActivarCuenta interDesActivarCuenta = new InternalDesActivarCuenta();
        InternalFrameEditar.add(interDesActivarCuenta);
        interDesActivarCuenta.setVisible(true);
    }//GEN-LAST:event_btn_DesActivarCuentaMouseClicked

    private void btn_EntrarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EntrarPerfilMouseClicked
        InternalFrameEditar.getContentPane().removeAll();
        InternalFrameEditar.setVisible(true);
        InternalEntrarPerfil interEntrarPerfil = new InternalEntrarPerfil();
        InternalFrameEditar.add(interEntrarPerfil);
        interEntrarPerfil.setVisible(true);
    }//GEN-LAST:event_btn_EntrarPerfilMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame InternalFrameEditar;
    private javax.swing.JLabel btn_BuscarPersona;
    private javax.swing.JLabel btn_DesActivarCuenta;
    private javax.swing.JLabel btn_EntrarPerfil;
    private javax.swing.JLabel jLabelEditarPerfil;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
